version: '3.8'

services:
  web:
    build: ./menus_back
    command: python3 ./menus_back/manage.py runserver 0.0.0.0:8001
    expose:
      - 8001
    volumes:
      - .:/code
    ports:
      - "8001:8001"

  nginx:
    build: ./nginx
    ports:
      - "81:80"
    depends_on:
      - web
    volumes:
      - .:/code
