version: '3.8'

services:
  web:
    build: ./menus_back
    command: python3 ./menus_back/manage.py runserver 0.0.0.0:8001
    expose:
      - 8001
    depends_on:
      - db_01
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    networks:
      - django_network

  nginx:
    build: ./nginx
    ports:
      - "81:80"
    depends_on:
      - web
    volumes:
      - .:/code
    networks:
      - django_network

  db_01:
    image: "postgres:15-bullseye"
    restart: always
    volumes:
      - ./docker/dumps:/docker-entrypoint-initdb.d/
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres123321
      - POSTGRES_USER=postgres
      - POSTGRES_DB=menus
      - TZ=UTC
    networks:
      - django_network

networks:
    django_network:
        driver: bridge