# Generated by Django 4.2.2 on 2023-07-29 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('char_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('sign', models.CharField(blank=True, max_length=1)),
                ('from_left', models.BooleanField(blank=True, default=True)),
                ('separated', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('enabled', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='menu.currency')),
            ],
            options={
                'verbose_name': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Позициия меню',
                'ordering': ['item_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/images')),
            ],
            options={
                'verbose_name': 'Тип позиции меню',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='menu.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('enabled', models.BooleanField(blank=True, default=True)),
                ('address', models.TextField(null=True)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='active_restaurants', to='menu.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=128)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='menu.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=1.0)),
                ('status', models.CharField(choices=[('ordered', 'ordered'), ('preparing', 'preparing'), ('delivered', 'delivered')], default='ordered', max_length=128)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='menu.menuitem')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='menu.table'),
        ),
        migrations.CreateModel(
            name='MenuItemPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/images')),
                ('enabled', models.BooleanField(default=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Картинка позиции меню',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='menu.menuitemtype'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='menu.menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='menus', to='menu.restaurant'),
        ),
    ]
