# Generated by Django 4.2.2 on 2023-07-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['item_type', 'id'], 'verbose_name': 'Позициия меню'},
        ),
        migrations.AddField(
            model_name='menuitemtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitemtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/images'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='menu.menuitemtype'),
        ),
        migrations.AlterField(
            model_name='menuitempicture',
            name='image',
            field=models.ImageField(upload_to='items/images'),
        ),
        migrations.AlterField(
            model_name='menuitempicture',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menu.menuitem'),
        ),
    ]
