# Generated by Django 4.2.2 on 2023-07-15 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_currency_restaurant_menu_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='menu.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=128)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='menu.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=1.0)),
                ('status', models.CharField(choices=[('ordered', 'ordered'), ('preparing', 'preparing'), ('delivered', 'delivered')], default='ordered', max_length=128)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='menu.menuitem')),
            ],
        ),
    ]
