# Generated by Django 4.2.2 on 2023-07-15 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menu_restaurant_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='menu.currency'),
        ),
    ]
