# Generated by Django 4.2.2 on 2023-07-15 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_menu_currency_restaurant_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='currency',
        ),
        migrations.AddField(
            model_name='menu',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='menu.currency'),
        ),
    ]
