# Generated by Django 4.2.2 on 2023-07-24 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_restaurant_currency_menu_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitempicture',
            options={'ordering': ['pk'], 'verbose_name': 'Картинка позиции меню'},
        ),
        migrations.RemoveField(
            model_name='menuitempicture',
            name='order',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='menu.menu'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.order'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='active_restaurants', to='menu.menu'),
        ),
    ]
