version: "3.8"

services:
  db:
    image: "postgres:15-bullseye"
    restart: always
    volumes:
      - ./docker/dumps:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=UTC
    ports:
      - "6432:6432"
